=== wol101/GaitSym_Wii_Kinect/GaitSymODE/xml/gaitsymode.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    
    <!-- This schema was initially generated using trang and then modified by hand -->
    
    <!-- these are some simple data types that are widely used -->
    
    <!-- mathematical types -->
    
    <xs:simpleType name="p-number-type">
        <xs:restriction base="xs:double">
            <xs:maxInclusive value="1.0"/>
            <xs:minInclusive value="0.0"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:simpleType name="list-of-doubles">
        <xs:list itemType="xs:double"/>
    </xs:simpleType>

    <xs:simpleType name="list-of-p-numbers">
        <xs:list itemType="p-number-type"/>
    </xs:simpleType>

    <xs:simpleType name="vector-type">
        <xs:restriction base="list-of-doubles">
            <xs:length value="3"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:simpleType name="colour-type">
        <xs:restriction base="list-of-p-numbers">
            <xs:length value="4"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:simpleType name="quaternion-type">
        <xs:restriction base="list-of-doubles">
            <xs:length value="4"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:simpleType name="plane-type">
        <xs:restriction base="list-of-doubles">
            <xs:length value="4"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:simpleType name="moi-type">
        <xs:restriction base="list-of-doubles">
            <xs:length value="6"/>
        </xs:restriction>
    </xs:simpleType>
    
    <!-- File name type -->
    <xs:simpleType name="file-name-type">
        <xs:restriction base="xs:anyURI">
        </xs:restriction>
    </xs:simpleType>
    
    <!-- enumerated types -->
    
    <xs:simpleType name="fitness-type-type">
        <xs:restriction base="xs:string">	
            <xs:enumeration value="DistanceTravelled"/>
            <xs:enumeration value="KinematicMatch"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:simpleType name="joint-type-type">
        <xs:restriction base="xs:string">	
            <xs:enumeration value="Hinge"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:simpleType name="geom-type-type">
        <xs:restriction base="xs:string">	
            <xs:enumeration value="CappedCylinder"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:simpleType name="strain-model-type">
        <xs:restriction base="xs:string">	
            <xs:enumeration value="Square"/>
            <xs:enumeration value="Linear"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:simpleType name="muscle-type-type">
        <xs:restriction base="xs:string">	
            <xs:enumeration value="UmbergerGerritsenMartin"/>
            <xs:enumeration value="MinettiAlexander"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:simpleType name="strap-type-type">
        <xs:restriction base="xs:string">	
            <xs:enumeration value="TwoPoint"/>
            <xs:enumeration value="ThreePoint"/>
            <xs:enumeration value="CylinderWrap"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:simpleType name="driver-type-type">
        <xs:restriction base="xs:string">	
            <xs:enumeration value="Cyclic"/>
            <xs:enumeration value="Step"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:simpleType name="target-data-type-type">
        <xs:restriction base="xs:string">	
            <xs:enumeration value="XP"/>
            <xs:enumeration value="YP"/>
            <xs:enumeration value="ZP"/>
            <xs:enumeration value="Q0"/>
            <xs:enumeration value="Q1"/>
            <xs:enumeration value="Q2"/>
            <xs:enumeration value="Q3"/>
            <xs:enumeration value="XV"/>
            <xs:enumeration value="YV"/>
            <xs:enumeration value="ZV"/>
            <xs:enumeration value="XRV"/>
            <xs:enumeration value="YRV"/>
            <xs:enumeration value="ZRV"/>
        </xs:restriction>
    </xs:simpleType>
    

  <xs:element name="GAITSYMODE">
    <xs:complexType>
      <xs:sequence>
          <xs:element minOccurs='1' maxOccurs="1" ref="GLOBAL"/>
        <xs:element minOccurs='0' maxOccurs="1" ref="INTERFACE"/>
        <xs:element minOccurs='0' maxOccurs="1" ref="ENVIRONMENT"/>
        <xs:element minOccurs='0' maxOccurs="unbounded" ref="BODY"/>
        <xs:element minOccurs='0' maxOccurs="unbounded" ref="JOINT"/>
        <xs:element minOccurs='0' maxOccurs="unbounded" ref="GEOM"/>
        <xs:element minOccurs='0' maxOccurs="unbounded" ref="MUSCLE"/>
        <xs:element minOccurs='0' maxOccurs="unbounded" ref="DRIVER"/>
        <xs:element minOccurs='0' maxOccurs="unbounded" ref="DATATARGET"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  
  <xs:element name="GLOBAL">
    <xs:complexType>
      <xs:attribute name="AllowInternalCollisions" use="required" type="xs:boolean"/>
      <xs:attribute name="BMR" use="required" type="xs:double"/>
      <xs:attribute name="CFM" use="required" type="xs:double"/>
      <xs:attribute name="ContactMaxCorrectingVel" use="required" type="xs:double"/>
      <xs:attribute name="ContactSurfaceLayer" use="required" type="xs:double"/>
      <xs:attribute name="DistanceTravelledBodyID" use="required" type="xs:IDREF"/>
      <xs:attribute name="ERP" use="required" type="xs:double"/>
      <xs:attribute name="FitnessType" use="required" type="fitness-type-type"/>
      <xs:attribute name="GravityVector" use="required" type="vector-type"/>
      <xs:attribute name="IntegrationStepSize" use="required" type="xs:double"/>
      <xs:attribute name="MechanicalEnergyLimit" use="required" type="xs:double"/>
      <xs:attribute name="MetabolicEnergyLimit" use="required" type="xs:double"/>
      <xs:attribute name="TimeLimit" use="required" type="xs:double"/>
      
      <xs:attribute name='MungeModelState' use='optional' type='xs:boolean'/>
      <xs:attribute name='OutputModelStateFilename' use='optional' type='file-name-type'/>
      <xs:attribute name='OutputKinematicsFile' use='optional' type='file-name-type'/>
      <xs:attribute name='OutputModelStateAtTime' use='optional' type='xs:double'/>
      <xs:attribute name='OutputModelStateAtCycle' use='optional' type='xs:double'/>
    </xs:complexType>
  </xs:element>
  
  <xs:element name="INTERFACE">
    <xs:complexType>
      <xs:attribute name="TrackBodyID" use="optional" type="xs:IDREF"/>
      <xs:attribute name="BodyAxisSize" use="optional" type="vector-type"/>
      <xs:attribute name="BodyColour" use="optional" type="colour-type"/>
      <xs:attribute name="EnvironmentAxisSize" use="optional" type="vector-type"/>
      <xs:attribute name="EnvironmentColour" use="optional" type="colour-type"/>
      <xs:attribute name="GeomColour" use="optional" type="colour-type"/>
      <xs:attribute name="JointAxisSize" use="optional" type="vector-type"/>
      <xs:attribute name="JointColour" use="optional" type="colour-type"/>
      <xs:attribute name="StrapColour" use="optional" type="colour-type"/>
      <xs:attribute name="StrapCylinderColour" use="optional" type="colour-type"/>
      <xs:attribute name="StrapCylinderLength" use="optional" type="xs:double"/>
      <xs:attribute name="StrapRadius" use="optional" type="xs:double"/>
      <xs:attribute name="StrapForceColour" use="optional" type="colour-type"/>
      <xs:attribute name="StrapForceRadius" use="optional" type="xs:double"/>
      <xs:attribute name="StrapForceScale" use="optional" type="xs:double"/>
    </xs:complexType>
  </xs:element>
  
  <xs:element name="ENVIRONMENT">
    <xs:complexType>
      <xs:attribute name="Plane" use="required" type="plane-type"/>
    </xs:complexType>
  </xs:element>
  
  <xs:element name="BODY">
    <xs:complexType>
      <xs:attribute name="AngularVelocity" use="required" type="vector-type"/>
      <xs:attribute name="GraphicFile" use="required" type="file-name-type"/>
      <xs:attribute name="ID" use="required" type="xs:ID"/>
      <xs:attribute name="LinearVelocity" use="required"/>
      <xs:attribute name="MOI" use="required" type="moi-type"/>
      <xs:attribute name="Mass" use="required" type="xs:double"/>
      <xs:attribute name="Position" use="required" type="vector-type"/>
      <xs:attribute name="Quaternion" use="required" type="quaternion-type"/>
      <xs:attribute name="Scale" use="required" type="xs:double"/>
    </xs:complexType>
  </xs:element>
  
  <xs:element name="JOINT">
    <xs:complexType>
      <xs:attribute name="Body1ID" use="required" type="xs:IDREF"/>
      <xs:attribute name="Body2ID" use="required" type="xs:IDREF"/>
      <xs:attribute name="HingeAnchor" use="required" type="vector-type"/>
      <xs:attribute name="HingeAxis" use="required" type="vector-type"/>
      <xs:attribute name="ID" use="required" type="xs:ID"/>
      <xs:attribute name="ParamHiStop" use="required" type="xs:double"/>
      <xs:attribute name="ParamLoStop" use="required" type="xs:double"/>
      <xs:attribute name="StartAngleReference" use="required" type="xs:double"/>
      <xs:attribute name="Type" use="required" type="joint-type-type"/>
    </xs:complexType>
  </xs:element>
  
  <xs:element name="GEOM">
    <xs:complexType>
      <xs:attribute name="BodyID" use="required" type="xs:IDREF"/>
      <xs:attribute name="ID" use="required" type="xs:ID"/>
      <xs:attribute name="Length" use="required" type="xs:double"/>
      <xs:attribute name="Position" use="required" type="vector-type"/>
      <xs:attribute name="Quaternion" use="required" type="quaternion-type"/>
      <xs:attribute name="Radius" use="required" type="xs:double"/>
      <xs:attribute name="Type" use="required" type="geom-type-type"/>
    </xs:complexType>
  </xs:element>
  
  <xs:element name="MUSCLE">
    <xs:complexType>
      <xs:attribute name="Aerobic" use="required" type="xs:boolean"/>
      <xs:attribute name="AllowReverseWork" use="required" type="xs:boolean"/>
      <xs:attribute name="CylinderBodyID" type="xs:IDREF"/>
      <xs:attribute name="CylinderPosition" type="vector-type"/>
      <xs:attribute name="CylinderQuaternion" type="quaternion-type"/>
      <xs:attribute name="CylinderRadius" type="xs:double"/>
      <xs:attribute name="FastTwitchProportion" use="required" type="xs:double"/>
      <xs:attribute name="FibreLength" use="required" type="xs:double"/>
      <xs:attribute name="ForcePerUnitArea" use="required" type="xs:double"/>
      <xs:attribute name="ID" use="required" type="xs:ID"/>
      <xs:attribute name="Insertion" use="required" type="vector-type"/>
      <xs:attribute name="InsertionBodyID" use="required" type="xs:IDREF"/>
      <xs:attribute name="MuscleDensity" use="required" type="xs:double"/>
      <xs:attribute name="Origin" use="required" type="vector-type"/>
      <xs:attribute name="OriginBodyID" use="required" type="xs:IDREF"/>
      <xs:attribute name="PCA" use="required" type="xs:double"/>
      <xs:attribute name="ParallelStrainAtFmax" use="required" type="xs:double"/>
      <xs:attribute name="ParallelStrainModel" use="required" type="strain-model-type"/>
      <xs:attribute name="SerialStrainAtFmax" use="required" type="xs:double"/>
      <xs:attribute name="SerialStrainModel" use="required" type="strain-model-type"/>
      <xs:attribute name="Strap" use="required" type="strap-type-type"/>
      <xs:attribute name="TendonLength" use="required" type="xs:double"/>
      <xs:attribute name="Type" use="required" type="muscle-type-type"/>
      <xs:attribute name="VMaxFactor" use="required" type="xs:double"/>
      <xs:attribute name="ActivationK" use="required" type="xs:double"/>
      <xs:attribute name="Width" use="required" type="xs:double"/>
    </xs:complexType>
  </xs:element>
  
  <xs:element name="DRIVER">
      <xs:complexType>
          <xs:attribute name="DurationValuePairs" use="required" type="list-of-doubles"/>
          <xs:attribute name="ID" use="required" type="xs:ID"/>
          <xs:attribute name="Target" use="required" type="xs:IDREF"/>
          <xs:attribute name="Type" use="required" type="driver-type-type"/>
      </xs:complexType>
  </xs:element>
  
  <xs:element name="DATATARGET">
      <xs:complexType>
          <xs:attribute name="DataType" use="required" type="target-data-type-type"/>
          <xs:attribute name="DurationValuePairs" use="required" type="list-of-doubles"/>
          <xs:attribute name="ID" use="required" type="xs:ID"/>
          <xs:attribute name="Target" use="required" type="xs:IDREF"/>
          <xs:attribute name="Type" use="required" type="driver-type-type"/>
          <xs:attribute name="Weight" use="optional" type="xs:double"/>
      </xs:complexType>
  </xs:element>
</xs:schema>

=== wol101/GaitSym_Wii_Kinect/GaitSymODE/xml/trex-limits/trex.xml
<?xml version="1.0" encoding="UTF-8"?>
<GAITSYMODE 
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:noNamespaceSchemaLocation="gaitsymode.xsd">

<!--
This is based on Paul's 1998 reconstruction

This is the 30% leg mass version
-->

<GLOBAL IntegrationStepSize="1e-3"
 GravityVector="0.0 0.0 -9.81"
 ERP="0.2"
 CFM="1e-10"
 ContactMaxCorrectingVel="10"
 ContactSurfaceLayer="0.001"
 AllowInternalCollisions="true"
 BMR="0"
 TimeLimit="10"
 MetabolicEnergyLimit="0"
 MechanicalEnergyLimit="0"
 FitnessType="DistanceTravelled"
 DistanceTravelledBodyID="Torso"
/>    

<INTERFACE EnvironmentAxisSize="1 1 1"
 EnvironmentColour="0.5 0.5 1.0 1.0"
 BodyAxisSize="0.2 0.2 0.2"
 BodyColour="0.91 0.85 0.79 1.0"
 JointAxisSize="0.5 0.5 0.5"
 JointColour="0 1 0 1"
 GeomColour="0 0 1 0.5"
 StrapColour="1 0 0 1" 
 StrapRadius="0.02"
 StrapForceColour="1 0 0 0.5"
 StrapForceRadius="0.1"
 StrapForceScale="0.0000001"
 StrapCylinderColour="0 1 1 0.5"
 StrapCylinderLength="0.5"
/>

<ENVIRONMENT Plane="0 0 1 -100000"
/>

<!-- 
Bodies
-->

<!--
Local coordinates are with the distal/caudal axis as the x axis, ventral is z, and y is left
Global coordinates are x forward; y left; z up
For a human in the anatomical position converting from local to global is a 90 degree rotation about the y axis

Quaternions are (qs,qx,qy,qz)
-->

<BODY ID="Torso"
 GraphicFile="Torso.obj"
 Scale="2.07"
 Mass="3990"
 MOI="1180.13 11801.3 11801.3 0 0 0"
 Position="0.53096426057173696 6.7071425828002835e-22 2.7920265582972226 "
 Quaternion="0.16896441364456213 -1.729323271608199e-23 -0.98562215220729965 1.807165515367351e-21 "
 LinearVelocity="10.5361    0.0000    0.7647"
 AngularVelocity="0.0000    0.1616    0.0000"
/>

<BODY ID="RightThigh"
 GraphicFile="RightThigh.obj"
 Scale="1.11"
 Mass="471"
 MOI="8.81 88.1 88.1 0 0 0"
 Position="0.21771317034669374 -3.6134792189750838e-22 2.5522666254509452 "
 Quaternion="0.8475559878894211 -1.6670892954561007e-21 0.53070598959573412 -6.9998230651276817e-22 "
 LinearVelocity="12.6860    0.0000    1.6396"
 AngularVelocity="0.0000    -4.8156    0.0000"
/>

<BODY ID="RightLeg"
 GraphicFile="RightLeg.obj"
 Scale="1.21"
 Mass="230"
 MOI="2.73 27.3 27.3 0 0 0"
 Position="0.17289863275034334 -4.2575998490005549e-21 1.470384188279368 "
 Quaternion="0.4796365575182433 -1.1206721440689495e-21 0.87746724878598681 -1.4182060150968484e-21 "
 LinearVelocity="18.4190    0.0000    1.9320"
 AngularVelocity="0.0000    -4.9105    0.0000"
/>

<BODY ID="RightFoot"
 GraphicFile="RightFoot.obj"
 Scale="1.18"
 Mass="155"
 MOI="1.92 19.2 19.2 0 0 0"
 Position="0.48752818320748437 -6.2172494675516635e-21 0.86730950164326825 "
 Quaternion="0.99765494346476302 -1.7992397922379096e-21 0.068444238474253141 1.7438607332006407e-22 "
 LinearVelocity="20.9132    0.0000    6.5568"
 AngularVelocity="0.0000    -8.3330    0.0000"
/>

<BODY ID="LeftThigh"
 GraphicFile="LeftThigh.obj"
 Scale="1.11"
 Mass="471"
 MOI="8.81 88.1 88.1 0 0 0"
 Position="0.05241544958355681 -6.2197458593359921e-22 2.5068583944339449 "
 Quaternion="0.73663135035727678 -1.5078050196693203e-21 0.67629450217402698 -9.9571140177618368e-22 "
 LinearVelocity="8.5777    0.0000    0.7983"
 AngularVelocity="0.0000    4.2326    0.0000"
/>

<BODY ID="LeftLeg"
 GraphicFile="LeftLeg.obj"
 Scale="1.21"
 Mass="230"
 MOI="2.73 27.3 27.3 0 0 0"
 Position="-0.39891601723621845 -4.3261237745066344e-21 1.5460575263898744 "
 Quaternion="0.2803738928795888 -7.8489723314239816e-22 0.95989086889684749 -1.6270973896540739e-21 "
 LinearVelocity="4.9605    0.0000    1.8090"
 AngularVelocity="0.0000    2.3233    0.0000"
/>

<BODY ID="LeftFoot"
 GraphicFile="LeftFoot.obj"
 Scale="1.18"
 Mass="155"
 MOI="1.92 19.2 19.2 0 0 0"
 Position="-1.0280725060244313 -8.1569451546244271e-21 0.57781521715266138 "
 Quaternion="0.64159089132600089 -1.3631941670066686e-21 0.76704701822476806 -1.1850960892848206e-21 "
 LinearVelocity="2.0867    0.0000    3.3310"
 AngularVelocity="0.0000    3.0925    0.0000"
/>


<!--
Joints
-->

<JOINT ID="RightHip"
 Type="Hinge"
 Body1ID="Torso"
 Body2ID="RightThigh"
 HingeAnchor="0.55 0 0 "
 HingeAxis="0 1 0 "
 StartAngleReference="2.3623522614883266 "
 ParamLoStop="1.47"
 ParamHiStop="2.37"
/>

<JOINT ID="RightKnee"
 Type="Hinge"
 Body1ID="RightThigh"
 Body2ID="RightLeg"
 HingeAnchor="0.64 0 0 "
 HingeAxis="0 1 0 "
 StartAngleReference="-1.0224208332243778 "
 ParamLoStop="-2.04"
 ParamHiStop="-1.007"
/>

<JOINT ID="RightAnkle"
 Type="Hinge"
 Body1ID="RightLeg"
 Body2ID="RightFoot"
 HingeAnchor="0.61 0 0 "
 HingeAxis="0 1 0 "
 StartAngleReference="2.0042475593691487 "
 ParamLoStop="0.686"
 ParamHiStop="2.19"
/>

<JOINT ID="LeftHip"
 Type="Hinge"
 Body1ID="Torso"
 Body2ID="LeftThigh"
 HingeAnchor="0.55 0 0 "
 HingeAxis="0 1 0 "
 StartAngleReference="1.9957191502161813 "
 ParamLoStop="1.47"
 ParamHiStop="2.37"
/>

<JOINT ID="LeftKnee"
 Type="Hinge"
 Body1ID="LeftThigh"
 Body2ID="LeftLeg"
 HingeAnchor="0.64 0 0 "
 HingeAxis="0 1 0 "
 StartAngleReference="-1.0876878234956706 "
 ParamLoStop="-2.04"
 ParamHiStop="-1.007"
/>

<JOINT ID="LeftAnkle"
 Type="Hinge"
 Body1ID="LeftLeg"
 Body2ID="LeftFoot"
 HingeAnchor="0.61 0 0 "
 HingeAxis="0 1 0 "
 StartAngleReference="0.82479870969540969 "
 ParamLoStop="0.686"
 ParamHiStop="2.19"
/>

<!--
Collision Geoms
-->

<GEOM ID="RightFootContact1"
 Type="CappedCylinder"
 BodyID="RightFoot"
 Position="0.52 0 0"
 Quaternion="0.0000000000000000 0.0000000000000000 0.7071067811865475 0.7071067811865476"
 Radius="0.05"
 Length="0.5"
/>

<GEOM ID="LeftFootContact1"
 Type="CappedCylinder"
 BodyID="LeftFoot"
 Position="0.52 0 0"
 Quaternion="0.0000000000000000 0.0000000000000000 0.7071067811865475 0.7071067811865476"
 Radius="0.05"
 Length="0.5"
/>


<!--
Muscles
-->


<MUSCLE Type="UmbergerGerritsenMartin"
 Strap="TwoPoint"
 ID="RightHipExtensor"
 OriginBodyID="Torso"
 Origin="1.28 0.0 -0.10"
 InsertionBodyID="RightThigh"
 Insertion="-0.08 0.0 -0.09"
 PCA="1.14"
 FibreLength="0.27"
 TendonLength="0.63"
 SerialStrainModel="Square"
 SerialStrainAtFmax="0.06"
 ParallelStrainModel="Square"
 ParallelStrainAtFmax="0.6"
 ForcePerUnitArea="250000"
 VMaxFactor="12"
 Width="0.97"
 FastTwitchProportion="0.43"
 MuscleDensity="1059.7"
 Aerobic="true"
 AllowReverseWork="true"
/>

<MUSCLE Type="UmbergerGerritsenMartin"
 Strap="TwoPoint"
 ID="RightHipFlexor"
 OriginBodyID="Torso"
 Origin="0.12 0.0 -0.63"
 InsertionBodyID="RightThigh"
 Insertion="-0.33 0.0 0.20"
 PCA="0.63"
 FibreLength="0.21"
 TendonLength="0.51"
 SerialStrainModel="Square"
 SerialStrainAtFmax="0.06"
 ParallelStrainModel="Square"
 ParallelStrainAtFmax="0.6"
 ForcePerUnitArea="250000"
 VMaxFactor="12"
 Width="0.97"
 FastTwitchProportion="0.43"
 MuscleDensity="1059.7"
 Aerobic="true"
 AllowReverseWork="true"
/>

<MUSCLE Type="UmbergerGerritsenMartin"
 Strap="CylinderWrap"
 ID="RightKneeExtensor"
 OriginBodyID="RightThigh"
 Origin="-0.02 0.0 0.16"
 InsertionBodyID="RightLeg"
 Insertion="-0.51 0.0 0.20"
 CylinderBodyID="RightLeg"
 CylinderPosition="-0.60 0.0 0.0"
 CylinderRadius="0.18"
 CylinderQuaternion="-0.7071067811865475 0.7071067811865476 0.0000000000000000 0.0000000000000000"
 PCA="1.79"
 FibreLength="0.17"
 TendonLength="0.85"
 SerialStrainModel="Square"
 SerialStrainAtFmax="0.06"
 ParallelStrainModel="Square"
 ParallelStrainAtFmax="0.6"
 ForcePerUnitArea="250000"
 VMaxFactor="12"
 Width="0.97"
 FastTwitchProportion="0.43"
 MuscleDensity="1059.7"
 Aerobic="true"
 AllowReverseWork="true"
/>

<MUSCLE Type="UmbergerGerritsenMartin"
 Strap="TwoPoint"
 ID="RightKneeFlexor"
 OriginBodyID="RightThigh"
 Origin="0.17 0.0 -0.02"
 InsertionBodyID="RightLeg"
 Insertion="-0.39 0.0 -0.17"
 PCA="0.51"
 FibreLength="0.26"
 TendonLength="0.11"
 SerialStrainModel="Square"
 SerialStrainAtFmax="0.06"
 ParallelStrainModel="Square"
 ParallelStrainAtFmax="0.6"
 ForcePerUnitArea="250000"
 VMaxFactor="12"
 Width="0.97"
 FastTwitchProportion="0.43"
 MuscleDensity="1059.7"
 Aerobic="true"
 AllowReverseWork="true"
/>

<!--dorsiflexion-->
<MUSCLE Type="UmbergerGerritsenMartin"
 Strap="TwoPoint"
 ID="RightAnkleExtensor"
 OriginBodyID="RightLeg"
 Origin="-0.18 0.0 0.08"
 InsertionBodyID="RightFoot"
 Insertion="-0.5 0.0 0.03"
 PCA="0.31"
 FibreLength="0.21"
 TendonLength="0.57"
 SerialStrainModel="Square"
 SerialStrainAtFmax="0.06"
 ParallelStrainModel="Square"
 ParallelStrainAtFmax="0.6"
 ForcePerUnitArea="250000"
 VMaxFactor="12"
 Width="0.97"
 FastTwitchProportion="0.43"
 MuscleDensity="1059.7"
 Aerobic="true"
 AllowReverseWork="true"
/>

<!--plantarflexion-->
<MUSCLE Type="UmbergerGerritsenMartin"
 Strap="CylinderWrap"
 ID="RightAnkleFlexor"
 OriginBodyID="RightLeg"
 Origin="-0.45 0.0 -0.14"
 InsertionBodyID="RightFoot"
 Insertion="-0.61 0.0 -0.18"
 CylinderBodyID="RightFoot"
 CylinderPosition="-0.65 0.0 0.0"
 CylinderRadius="0.12"
 CylinderQuaternion="0.7071067811865475 0.7071067811865476 0.0000000000000000 0.0000000000000000"
 PCA="0.61"
 FibreLength="0.25"
 TendonLength="1.10"
 SerialStrainModel="Square"
 SerialStrainAtFmax="0.06"
 ParallelStrainModel="Square"
 ParallelStrainAtFmax="0.6"
 ForcePerUnitArea="250000"
 VMaxFactor="12"
 Width="0.97"
 FastTwitchProportion="0.43"
 MuscleDensity="1059.7"
 Aerobic="true"
 AllowReverseWork="true"
/>

<MUSCLE Type="UmbergerGerritsenMartin"
 Strap="TwoPoint"
 ID="LeftHipExtensor"
 OriginBodyID="Torso"
 Origin="1.28 0.0 -0.10"
 InsertionBodyID="LeftThigh"
 Insertion="-0.08 0.0 -0.09"
 PCA="1.14"
 FibreLength="0.27"
 TendonLength="0.63"
 SerialStrainModel="Square"
 SerialStrainAtFmax="0.06"
 ParallelStrainModel="Square"
 ParallelStrainAtFmax="0.6"
 ForcePerUnitArea="250000"
 VMaxFactor="12"
 Width="0.97"
 FastTwitchProportion="0.43"
 MuscleDensity="1059.7"
 Aerobic="true"
 AllowReverseWork="true"
/>

<MUSCLE Type="UmbergerGerritsenMartin"
 Strap="TwoPoint"
 ID="LeftHipFlexor"
 OriginBodyID="Torso"
 Origin="0.12 0.0 -0.63"
 InsertionBodyID="LeftThigh"
 Insertion="-0.33 0.0 0.20"
 PCA="0.63"
 FibreLength="0.21"
 TendonLength="0.51"
 SerialStrainModel="Square"
